test fails like this:
<nil> isOverlap true
a_ (100ms) f_ (300ms) f/ (200ms) j_ (200ms) j/
--- FAIL: Test_manInTheMiddle_asdf_TwoJoinedCombos (0.00s)
panic: I am confused. timeSub should be a positive duration [recovered]

---

The buffer contains too much.

Maybe create a state.Validate() function which I call often during
development. So that the place which creates invalid states get detected soon.